### ISSUE TITLE
add support for fasta.txt and .txt extension

### ISSUE THREAD

**Issue by ajasja** [ajasja/af2slurm#6]
On windows systems the extension is often hidden and files look like they have a .fasta extension but are in fact fast.txt.

It would be great if these files (and perhaps a .txt) would be handled transparently.

**Comment by Poko18** [comment]
'.fasta', '.a3m' and '.fasta.txt' are now handled.

**Comment by ajasja** [comment]
Closed in https://github.com/ajasja/af2slurm/pull/8
